version: '3'
services:
  node:
    build: ./node
    container_name: node
    # entrypoint: dockerize -wait tcp://db -timeout 30s docker-entrypoint.sh
    networks:
      - desafionet
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - db

  db:
    build: ./mysql
    container_name: mysql
    networks:
      - desafionet
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - desafionet
    ports:
      - "8080:80"

networks:
  desafionet:
    driver: bridge

volumes:
  db_data: