services:

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: node-desafio
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - desafionet
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - db

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: db-desafio
    container_name: db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    tty: true
    ports:
      - "3386:3386"
    networks:
      - desafionet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-desafio    
    container_name: nginx
    networks:
      - desafionet
    ports:
      - "8080:80"
    depends_on:
    - node

networks:
  desafionet:
    driver: bridge
